### ISSUE TITLE
'unknown option' errors for common options

### ISSUE THREAD

**Issue by roycewilliams** [sektioneins/sshdcc#1]
Getting some `unknown option` errors on an initial vanilla run of `./sshdcc -dc 'sudo sshd -f /dev/null -T'
` on Ubuntu 16.04 LTS.

```
(1) [WARNING] unknown option 'uselogin'
(2) [WARNING] unknown option 'gssapistorecredentialsonrekey'
(3) [WARNING] unknown option 'gssapikeyexchange'
(4) [WARNING] unknown option 'Protocol'
(5) [WARNING] unknown option 'UsePrivilegeSeparation'
(6) [WARNING] unknown option 'KeyRegenerationInterval'
(7) [WARNING] unknown option 'ServerKeyBits'
(8) [WARNING] unknown option 'RSAAuthentication'
(9) [WARNING] unknown option 'RhostsRSAAuthentication'
```
If this is due to a configuration or dependency problem, consider this a UX feature request to more directly detect and warn the user of such an issue. I can test or provide more information if needed.

**Comment by bef** [comment]
Ok. Please retry.
The original version included options for OpenSSH 7.7 only. Apparently there are older versions out there, too.
